version: "3.8"

services:
  optuna:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      STUDY_STORAGE_POSTGRES_URL: "postgresql://legalensdev:qfY0GGzoGn@db.legalens.internal:5432/optuna"
      VESPA_URL: "http://vespa-legalens.internal"
      VESPA_PORT: "8080"
      STUDY_NAME: "vespa_ranking_study"
    
    networks:
      - legalens

    depends_on:
      - legalens_backend_db 
      - vespa

networks:
  legalens:
    external: true
